#!/usr/bin/env ruby

require "bundler/setup"
require "epub_book"
require 'yaml'

# use like
# bin/create_book http://www.quanben5.com/n/jinyiyexing/xiaoshuo.html bookname
url,bookname,des_url = ARGV

#smtp setting
EpubBook.configure do |config|
  config.setting_file = './default_setting.yml'
end

EpubBook.create_book(url,bookname,des_url)

